name: Lint & Test Bundle

on:
  pull_request:
  push:
    branches: develop

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.2
        bundler-cache: true
    - name: Run rubocop to lint
      run: bundle exec rubocop
    - name: Set up asciidoctor binary
      run: sudo apt -y install asciidoctor
    - name: Set working directory
      run: cd $GITHUB_WORKSPACE
    - name: Run the default task
      run: bundle exec rake
