name: Publish Gem

on:
  pull_request:
    branches:
      - main
    types: [closed]
    paths:
      - 'lib/version.rb'
jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    permissions:
      id-token: write
      contents: write

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
          bundler-cache: true

      - name: Extract version from lib/version.rb
        run: |
          VERSION=$(ruby -r ./lib/version.rb -e 'puts Boost::VERSION')
          echo "$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Create Git tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag v${{ env.VERSION }}
          git push origin v${{ env.VERSION }}

      - name: Extract release notes from CHANGELOG.md
        id: changelog
        run: |
          CHANGELOG_TEXT=$(awk '/^## \[${{ env.VERSION }}\]/ {flag=1; next} /^## \[/ && flag {flag=0} flag' CHANGELOG.md)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$CHANGELOG_TEXT" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Build gem
        run: gem build *.gemspec

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v${{ env.VERSION }}"
          release_name: "v${{ env.VERSION }}"
          body: "${{ env.RELEASE_NOTES }}"
          draft: false
          prerelease: false

      - name: Publish to RubyGems
        uses: rubygems/release-gem@v1
